In [3]:
##Уровень 1
a=[15,32,0]
b=[-32,-18,25]
res=0
for i in range (len(a)):
    res =res+a[i]*b[i]
print(res)

-1056


In [19]:
import numpy as np

A = np.array([[5,10,1],[0,1,0],[9,3,6]])
B = np.array([[1,7,3],[0,2,0],[9,4,2]])
D = np.array([[5,1,8],[2,6,3],[1,3,0]])

C = A @ B
E = A @ D
DT = D.T
print(C)
print()
print(E)
print()
print(DT)

[[14 59 17]
 [ 0  2  0]
 [63 93 39]]

[[46 68 70]
 [ 2  6  3]
 [57 45 81]]

[[5 2 1]
 [1 6 3]
 [8 3 0]]


In [21]:
##Уровень 2
from scipy import linalg
import numpy as np

A = np.array([[100,200,1000],[350,150,55],[30,30,30]])
B = np.array([2600,1660,210])

C = linalg.solve(A,B)
print(C)


[4. 1. 2.]


In [29]:
from scipy import linalg
A = np.array([[1,3],[-1,2]])
F= np.linalg.inv(A)
print('x=',F[0,1])


x= -0.6000000000000001


In [39]:
## Обратный матрицы не будет существовать при det(A)=0 ,который находится по формуле x11*x22-x21*x12
a= float(input())
b= float(input())
d= float(input())
x= a*d/b
print('Обратной матрицы не существует при x=',x)

 2
 3
 -2


Обратной матрицы не существует при x= -1.3333333333333333
